// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:video_player/video_player.dart';
import 'dart:io';

// required: associates our `main.dart` with the code generated by Freezed
part 'home_model.freezed.dart';

@freezed
class HomeModel with _$HomeModel {
  const factory HomeModel({
    required bool vertical,
    required VideoPlayerController? firstVideoController,
    required VideoPlayerController? secondVideoController,
    required File? firstVideo,
    required File? secondVideo,
  }) = _HomeModel;
}
