// This file is "main.dart"
// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'landing_model.freezed.dart';

@freezed
class LandingModel with _$LandingModel {
  const factory LandingModel({
    required bool lightmode, required String currentLanguage,
  }) = _LandingModel;
}
